services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
      - secrets/mariadb.env
      - secrets/db-info.env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
      - secrets/wordpress.env
      - secrets/db-info.env
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - wordpress

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge
